### ISSUE TITLE
JsonCommandsAsync.GetAsync<T> throws JsonException when not found.

### ISSUE THREAD

**Issue by dominkomin** [redis/NRedisStack#198]
**NRedisStack Version**: 0.10.1

**Redis Stack Version**: 7.2.2

**Description**: JsonCommandsAsync.GetAsync<T> throws JsonException when entry not found, while probably default(T) should be returned.

**Comment by shacharPash** [comment]
Hi @dominkomin, thanks for submitting this issue!
This is indeed a bug, the problem is in cases where Redis returns null but the result is still considered a `BulkString`, therefore the function tries to `Deserialize` which causes a `JsonException`.
According to what I saw, the problem also exists in `Get<T>` and not only in the asynchronous version.
I added a null check and now it should work.
